import Head from "next/head";
import TopContainer from "@/src/components/home/top-container";
import MiddleContainer from "@/src/components/home/middle-container";
import Footer from "../components/home/footer/Footer";

export const metadata = {
  title: "Nextlevelbot - Automation Trading with Tradingview",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Head>
        <title>NextLevelbot - Automation Trading with Tradingview</title>
      </Head>
      <TopContainer />
      <MiddleContainer />
      <Footer />
    </div>
  );
};

export default page;
